---
version: "1"
detectorOptions:
    pollInterval: 3
    timeout: 3
profiles:
  company-docked-three-monitors:
    on_enable:
      exec:
        command: "/bin/echo Hello World!"
      screenlayout:
        layout: "company-office-three-monitors-special"
    on_disable:
      screenlayout:
        layout: "disable"
    trigger:
      acpid:
        docked: false
      network:
        enp0s31f6:
            ip: "*"
      screens:
        count: 3
        connected:
          - DP1-1
          - DP1-2
          - DP1-3
  company-on-the-go:
    on_enable:
      exec:
        command: "/bin/echo Hello World!"
      screenlayout:
        layout: "company-office-three-monitors-special"
    on_disable:
      screenlayout:
        layout: "disable"
    trigger:
      acpid:
        docked: true
      network:
        wlp1s0:
          network_name: "*"
      screens:
        count: 1
        connected:
          - eDP1
  home:
    on_enable:
      exec:
        command: "/bin/echo Hello World!"
      screenlayout:
        layout: "home"
    on_disable:
      screenlayout:
        layout: "disable"
    trigger:
      acpid:
        docked: false
      network:
        enp0s31f6:
          ip: "*"
      screens:
        count: 3
        connected:
          - DP1-1
          - DP1-2
          - DP1-3
