---
version: "1"
pollerOptions:
  pollInterval: 3
  timeout: 3
triggersConfig:
  ipAddress:
    interfaces:
    - enp0s31f6
    - wlp1s0
actionsConfig:
  exec: {}
profiles:
- name: home
  onEnable:
    exec:
      command: "/bin/echo HELLO WORLD!"
#    libnotify:
#      delay: "5s"
#      message: "Profile enabled: home"
  onDisable:
    exec:
      command: "/bin/echo GOODBYE WORLD!"
    libnotify:
      delay: "5s"
      message: "Profile disabled: home"
      urgency: 2
  trigger:
    ipAddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.139/24
          key: 0
- name: test
  onEnable:
    exec:
      command: "/bin/echo HELLO WORLD 2!"
  onDisable:
    exec:
      command: "/bin/echo GOODBYE WORLD 2!"
  trigger:
    ipAddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.150/24
          key: 0
