---
version: "1"
pollerConfig:
  pollInterval: "3s"
  timeout: "5s"
triggersConfig:
  ipaddress:
    interfaces:
    - enp0s31f6
    - wlp1s0
  xrandr:
    xauthoritiy: /home/atrost/.Xauthoritiy
actionsConfig:
  exec: {}
profiles:
# profile: home
- name: home
  # waht to run when the profile is enabled
  onenable:
    exec:
      # the commands to run
      command: "/bin/echo HELLO WORLD!"
    # send a notification using libnotify
    libnotify:
      delay: "5s"
      title: "Profile enabled"
      message: "home"
  ondisable:
    exec:
      # the commands to run
      command: "/bin/echo GOODBYE WORLD!"
    # send a notification using libnotify
    libnotify:
      delay: "5s"
      title: "Profile disabled"
      message: "home"
      urgency: 2
  trigger:
    # ipaddress trigger
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.139/24
          key: 0
    xrandr:
      connectedcount: 2
- name: test
  onenable:
    exec:
      # the commands to run
      command: "/bin/echo HELLO WORLD 2!"
  ondisable:
    exec:
      # the commands to run
      command: "/bin/echo GOODBYE WORLD 2!"
  trigger:
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.150/24
          key: 0
