---
version: "1"
detectorOptions:
    pollInterval: 3
    timeout: 3
profiles:
  company-docked-three-monitors:
    on_enable:
      exec:
        command: "/usr/bin/ln -sf /home/atrost/Pictures/Desktop/lockscreen-three-monitors.png /home/atrost/Pictures/Desktop/lockscreen.png"
    on_disable:
      exec:
        command: "/usr/bin/ln -sf /home/atrost/Pictures/Desktop/lockscreen-single.png /home/atrost/Pictures/Desktop/lockscreen.png"
    trigger:
      acpid:
        docked: true
      network_enp0s31f6:
        ip: "10.20.0.77/23"
      screens:
        count: 3
        connected:
          - DP1-1
          - DP1-2
          - DP1-3
  company-on-the-go:
    on_enable:
      exec:
        command: "/usr/bin/ln -sf /home/atrost/Pictures/Desktop/lockscreen-three-monitors.png /home/atrost/Pictures/Desktop/lockscreen.png"
    on_disable:
      exec:
        command: "/usr/bin/ln -sf /home/atrost/Pictures/Desktop/lockscreen-single.png /home/atrost/Pictures/Desktop/lockscreen.png"
    trigger:
      acpid:
        docked: false
      network_wlp1s0:
        network_name: "*"
      screens:
        count: 1
        connected:
          - eDP1
  home:
    on_enable:
      exec:
        command: "/bin/echo Hello World!"
    on_disable:
      exec:
        command: "/usr/bin/ln -sf /home/atrost/Pictures/Desktop/lockscreen-single.png /home/atrost/Pictures/Desktop/lockscreen.png"
    trigger:
      acpid:
        docked: true
      network_enp0s31f6:
        options:
          addrsKey: 0
        ip: "192.168.1.139/24"
      screens:
        count: 3
        connected:
          - DP1-1
          - DP1-2
          - DP1-3
