---
version: "1"
pollerconfig:
  pollInterval: "3s"
  timeout: "5s"
triggersconfig:
  ipaddress:
    interfaces:
    - enp0s31f6
    - wlp1s0
  xrandr:
    xauthoritiy: /home/atrost/.Xauthoritiy
actionsconfig:
  exec: {}
profiles:
- name: home
  onenable:
    exec:
      command: /bin/echo
      args:
        - HELLO WORLD!
    libnotify:
      delay: "5s"
      message: "Profile enabled: home"
  ondisable:
    exec:
      command: /bin/echo
      args:
        - "GOODBYE WORLD!"
    libnotify:
      delay: "5s"
      message: "Profile disabled: home"
      urgency: 2
  trigger:
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.139/24
          key: 0
    xrandr:
      connectedcount: 2
- name: test
  onenable:
    exec:
      command: "/bin/echo HELLO WORLD 2!"
  ondisable:
    exec:
      command: /bin/echo
      args:
        - "GOODBYE WORLD 2!"
  trigger:
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.150/24
          key: 0
