---
version: "1"
pollerconfig:
  pollInterval: "3s"
  timeout: "5s"
triggersconfig:
  ipaddress:
    interfaces:
    - enp0s31f6
    - wlp1s0
  xrandr:
    xauthoritiy: /home/atrost/.Xauthoritiy
actionsconfig:
  exec: {}
profiles:
# profile: home
- name: home
  # waht to run when the profile is enabled
  onenable:
    exec:
      # the command to run
      command: /bin/echo
      # the arguments to add to the command
      args:
        - HELLO WORLD!
    # send a notification using libnotify
    libnotify:
      delay: "5s"
      title: "Profile enabled"
      message: "home"
  ondisable:
    exec:
      # the command to run
      command: /bin/echo
      # the arguments to add to the command
      args:
        - HELLO WORLD!
    # send a notification using libnotify
    libnotify:
      delay: "5s"
      title: "Profile disabled"
      message: "home"
      urgency: 2
  trigger:
    # ipaddress trigger
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.139/24
          key: 0
    xrandr:
      connectedcount: 2
- name: test
  onenable:
    exec:
      # the commands to run
      command: "/bin/echo HELLO WORLD 2!"
  ondisable:
    exec:
<<<<<<< HEAD
      # the commands to run
      command: "/bin/echo GOODBYE WORLD 2!"
=======
      command: /bin/echo
      args:
        - "GOODBYE WORLD 2!"
>>>>>>> c043a5178fb73a42c9789472cff82ae579c52a4b
  trigger:
    ipaddress:
      addresses:
        enp0s31f6:
          address: 192.168.1.150/24
          key: 0
